### ISSUE TITLE
Pod5 convert to_fast5 is losing signal data

### ISSUE THREAD

**Issue by ssomalra** [nanoporetech/pod5-file-format#132]
## Issue Description

Hello there,

I am attempting to convert my POD5 files to FAST5 files for use with downstream analysis tools such as nanopolish. However, I noticed that the FAST5 files are not storing the signal data present in the POD5 files. This issue is similar to the one describe here: https://github.com/nanoporetech/pod5-file-format/issues/128 . Although it was suggested that having VBZ-compression installed would resolve the problem, I am still experiencing this issue.

To verify the presence of the signal data in my FAST5 files, I used h5py:
<img width="512" alt="image" src="https://github.com/nanoporetech/pod5-file-format/assets/116883221/671d6034-3cfb-4233-a7b9-8a663421cbe5">

Additionally, I ran the pod5 view command on one of my POD5 files. Attached is a file containing a few lines of the output from this command:
[pod5_view_output.txt](https://github.com/user-attachments/files/15844293/pod5_view_output.txt)

I would appreciate any help with this issue. Thank you!

**Comment by Brooklyn12** [comment]
Did you end up finding the solution? I am trying to run an analysis that requires fast5, and when I use the pod5 convert to_fast5 no signals can be found on any of the reads on the fast5 file. When I run it on a non-converted fast5 it works great.

**Comment by ssomalra** [comment]
I realized my code to verify the presence of signal data had an error (line 4 should be 'Raw/Signal') and was able to identify the signal data in all my fast5 reads. I think the issue I was facing was either with Nanopolish or within the data itself.

**Comment by SLAment** [comment]
I am experiencing the same problem (am I missing something??)

I transformed my pod5 files like such: 
`pod5 convert to_fast5 path2pod5/*pod5 --output fast5/`

A `pod5 view file.pod5 | head -n5` call to my data looks like so: 
```
read_id	filename	read_number	channel	mux	end_reason	start_time	start_sample	duration	num_samples	minknow_events	sample_rate	median_before	predicted_scaling_scale	predicted_scaling_shift	tracked_scaling_scale	tracked_scaling_shift	num_reads_since_mux_change	time_since_mux_change	run_id	sample_id	experiment_id	flow_cell_id	pore_type
41506278-4c8a-4772-87fc-c9333deec5c9	FAX37548_pass_barcode01_fdceb05f_b1910f12_0.pod5	27	478	1	signal_positive	106.97960000	534898	1.52820000	7641	872	5000	202.30789185	19.13400459	92.03026581	-0.00000000	-0.00000000	1	7.57219982	fdceb05f-fb37-4e97-9109-f869d4e64f5e	pool1_2	nlrs	FAX37548	not_set
6e8e68b6-6f32-497c-a1c5-5a15c3a8bdbc	FAX37548_pass_barcode01_fdceb05f_b1910f12_0.pod5	43	274	1	signal_positive	110.45020000	552251	0.63600000	3180	416	5000	206.40859985	19.63545609	93.52126312	-0.00000000	-0.00000000	1	10.56760025	fdceb05f-fb37-4e97-9109-f869d4e64f5e	pool1_2	nlrs	FAX37548	not_set
d5db6cc9-0994-4ce9-9ab8-f0ec33fe3319	FAX37548_pass_barcode01_fdceb05f_b1910f12_0.pod5	65	247	1	signal_positive	112.15600000	560780	1.49840000	7492	925	5000	181.13900757	16.73853111	76.50327301	-0.00000000	-0.00000000	1	13.24040031	fdceb05f-fb37-4e97-9109-f869d4e64f5e	pool1_2	nlrs	FAX37548	not_set
c378a9bb-b7d9-457d-a676-15575b2e814d	FAX37548_pass_barcode01_fdceb05f_b1910f12_0.pod5	30	139	1	signal_positive	107.29740000	536487	8.51480000	42574	5278	5000	205.74470520	17.51976776	94.24188232	-0.00000000	-0.00000000	1	15.61240005	fdceb05f-fb37-4e97-9109-f869d4e64f5e	pool1_2	nlrs	FAX37548	not_set
```
But if I do as @ssomalra above (plus the fix), I don't get signal data.

```python
import h5py
file_path = "fast5/myfile.fast5"

def check_signal_in_fast5(file_path):
	with h5py.File(file_path, 'r') as fast5_file:
		signal_path = "Raw/Signal"
		if signal_path in fast5_file:
			print(f"Signal found in {signal_path}")
		else:
			print("No signal found")

check_signal_in_fast5(file_path)
```

Similarly if I do
```python
with h5py.File(file_path, "r") as f:
     if "Raw" in f: print("Raw signal found.")
```
I get nothing. 

Any help would be appreciated!

**Comment by 0x55555555** [comment]
Hi @SLAment ,

What is the output of the conversion from pod5 to fast5? What are the contents of the fast5 files?

Thanks,
- George

**Comment by SLAment** [comment]
Ah yes, of course, sorry!

I'm not sure if I'm doing this right, it's my first time working with fast5 files. I followed the instructions [here](https://denbi-nanopore-training-course.readthedocs.io/en/latest/basecalling/inspect_h5.html). 

Let's say I take one file called `example_bc01.pod5` and make it a fast5 file (`h5ls example_bc01.0_0.fast5`).

	> pod5 convert to_fast5 example_bc01.pod5 --output .
	Converting pod5s into 1 fast5 files. Please wait...
	4000 reads,	 313.5 MSamples,	 1/1 files,	 19.3 MB/s
	4000 reads,	 313.5 MSamples,	 1/1 files,	 19.3 MB/s
	Conversion complete

I can look for the first read as in my example in the post above. 

	> h5ls example_bc01.0_0.fast5/read_41506278-4c8a-4772-87fc-c9333deec5c9
	Raw                      Group
	channel_id               Group
	context_tags             Group
	tracking_id              Group

But if I try to see the raw signal:

	> h5ls -d example_bc01.0_0.fast5/read_41506278-4c8a-4772-87fc-c9333deec5c9/Raw
	Signal                   Dataset {7641}
    Data:
                 Unable to print data.

Thanks again,

Lorena

**Comment by 0x55555555** [comment]
The prints in your two messages seem contradictory - one has no `Raw` dataset, the other can't read the dataset?

From the second print, it looks like a normally formatted multi-read fast5 file, which you are unable to read the raw data?


Do you have the vbz compression plugin installed: https://github.com/nanoporetech/vbz_compression/releases

This is required to read raw data from pod5 files.

- George

**Comment by SLAment** [comment]
Hi George,

You lost me here... I've been working on a conda environment with an isolated installation of the `pod5` package (through the local pip of the environment) in a cluster where I don't have sudo privileges. So I put my `example_bc01.pod5` and `example_bc01.0_0.fast5` files locally on my laptop and installed HDFview. I also installed the vbz compression plugin locally as you suggested. The `example_bc01.0_0.fast5` file looks like this:

<img width="1363" alt="Image" src="https://github.com/user-attachments/assets/cb62eed9-04c1-47bd-92d6-0e7c069dc025" />


And clicking inside

<img width="1364" alt="Image" src="https://github.com/user-attachments/assets/7d065b66-dfd0-446a-a80d-d02991cbd29c" />


I understand the plugin is necessary to see fast5 files correctly with HDFview, but can that program also visualize pod5 files (as implied by your last comment)? I'm not sure what I'm looking for since I've never seen a "good" fast5 file. The pod5 files worked perfectly well when I basecalled them with Dorado, so they are presumably fine. 

If the `pod5 convert to_fast5 example_bc01.pod5 --output .` command was not the best way to transform the pod5 file to fast5, please advise on what alternative to use.

Thanks again for the input,

Lorena

**Comment by SLAment** [comment]
Hi George,

I tried clicking around, I would guess this is indeed the signal?

![Image](https://github.com/user-attachments/assets/b2157502-3372-4bf7-b780-d45ef9d02a34)

My issue is that I submitted the fast5 files into NCBI SRA (since they won't take pod5 files) and I got an error. Then I tried to do `h5ls -d example_bc01.0_0.fast5/read_41506278-4c8a-4772-87fc-c9333deec5c9/Raw` and I got `Unable to print data.` as I showed in the previous post, so I interpreted it as the signal data being missing. But it seems that's not it. Any idea why I can't visualize it with `h5ls`?

Thanks so much for your help and sorry for the confusion,

Lorena

**Comment by 0x55555555** [comment]
Hi @SLAment ,

Are you running `h5ls` on the same machine as the hdfview tool? If one can read the data, it surprises me the other cannot.

I would suggest you seek support at the NCBI as to why the submission failed?


The data in the signal dataset is compressed with the nanopore vbz compression format, this may be whats causing you issues, but I don't know that for sure.

Thanks,
- George

**Comment by SLAment** [comment]
Thanks George. I'm running `h5ls` in a conda environment and the vbz plugin was a global installation, so maybe that's why? Anyway, thanks a lot for the help and sorry for the confusion!
