### ISSUE TITLE
It looks like your running out of memory when trying to load the mapping.

### ISSUE THREAD

**Issue by yinyuanmtu** [nanoporetech/pod5-file-format#141]
It looks like your running out of memory when trying to load the mapping. 
You should try to be more specific with the input files as you're only searching for 0.001% of the reads 

You can get a mapping of read_id to filename using this:
```
pod5 view --include "read_id,filename" -o view.txt
```

filtering your input file list to only those that actually contain a read will fix your issue.

Kind regards, 
Rich

_Originally posted by @HalfPhoton in https://github.com/nanoporetech/pod5-file-format/issues/124#issuecomment-2090600530_

**Comment by yinyuanmtu** [comment]
@HalfPhoton, I am revisiting the old issue. I have created the view.txt file following your suggestion. Could you advise me how to proceed further using this view file to run pod5 filter? I couldn't find the argument to supply this view.txt file to filter the input pod5. Thanks!

**Comment by HalfPhoton** [comment]
Your initial problem was:
```text
Parsed 119 reads_ids from: readList.txt
Found 10706621 read_ids from 2677 inputs
```

You have many more files than reads. So it's a good idea to tell pod5 to only use the files that are actually useful for the process instead of everything. 

```bash
pod5 view --include "read_id,filename" -o view.txt
```

Will write all read_ids with their filename.

```text
read_id1 filename_001.pod5
read_id2 filename_012.pod5
....
read_idN filename_1931.pod5
```

You have a list of read_ids that you want so you can use `join` to get the lines with filenames for only the desired read ids. Then you can extract the filenames to get only the filenames that are useful to the subsetting process. 

```bash
sort view.txt -o view.sorted.txt
sort my_ids.txt -o my_ids.sorted.txt
join view.sorted.txt my_ids.sorted.txt | awk '{print $2}' | sort -u > useful_filenames.txt
```

With `useful_filenames.txt` you can now create a temporary directory symbolically linking these files so that subset doesn't need to search everything.

```bash
mkdir useful_files
for F in $(cat useful_filenames.txt); do
  ln -s existing_data/${F} useful_files/${F}
done;
```

Filter only using these symlink files:
```bash
pod5 filter useful_files/ --ids my_ids.txt -o useful_reads.pod5
```

Something like that 👍 

Best regards,
Rich
