### ISSUE TITLE
shift and scale values are always nans

### ISSUE THREAD

**Issue by lubitelpospat** [nanoporetech/pod5-file-format#155]
Hi folks,
I was looking through a few pod5 dRNAseq datasets, and it turned out that both predicted_scaling and tracked_scaling are always nans (shift and scale). Could you please:
1. Explain what those predicted scaling and tracked scaling are,
2. Why are they nans, should they be nans and whether there's some flag in dorado to get them to be some non-nan values,
3. Give some guidelines on which of these should be used for signal "normalization", so to say?

Thank you very much in advance for your response!

**Comment by 0x55555555** [comment]
Hi @lubitelpospat,

1. They were intended to help the basecaller scale the pico amp values into a sensible space for basecalling
2. The value's are Nans for some kit conditions because the feature in minknow is only enabled for certain conditions.
3. These values should not be consumed.

Thanks,
- George

**Comment by 0x55555555** [comment]
> Just to confirm - both of these shift & scale pairs should not be used by downstream applications, am I correct about that?

**Comment by lubitelpospat** [comment]
Thank you so much for your answers! Will mark this issue as closed.
