### ISSUE TITLE
Error:Unable to open the group "Raw": (Symbol table) Object not found

### ISSUE THREAD

**Issue by Vsd1106** [nanoporetech/pod5-file-format#52]
I have converted some single read fast5 files to multi read fast5 files using the ont-fast-api. When I try to convert those fast5 files to pod5 I am met with this error:Unable to open the group "Raw": (Symbol table) Object not found

**Comment by HalfPhoton** [comment]
Hi @Vsd1106 ,

This issue is likely with `ont-fast5-api` not `pod5` but hopefully we can resolve this issue here.

The `Raw` key mentioned in the error is  the `HDF5 Group` in a multi-read fast5 file which contains the signal data which is a required field. 

This error could be caused during the ont-fast5-api conversion where the input data might be corrupt or badly formatted. 

Can you please inspect the input file and the converted multi-read fast5 file with some HDF5 file viewer such as `HDFView` or manually with `h5py` to investigate further where this issue has come from?  

Kind regards,
Rich

**Comment by Vsd1106** [comment]
Yea there seems to be an error when converting it to a multi fast5 file:read_LomanLabz_E.coli_MG1655_3311_1_ch322_file50_strand.fast5 > Analyses > Basecall_2D_000 > Configuration > split_hairpin (Group)
KeyError: Unable to open object (InputEvents not found)
Can this be fixed by just deleting the single read fast5 files that are an issue?

**Comment by HalfPhoton** [comment]
Hi @Vsd1106 ,

I've spotted a duplicate issue raised on ont-fast5-api  [#77](https://github.com/nanoporetech/ont_fast5_api/issues/77).

Have you managed to resolve this issue since you raised these issues? If not, let's continue the conversation here to keep everything in one place. 

Kind regards,
Rich

**Comment by Vsd1106** [comment]
Hi Rich,
Sadly no, I think it was the single read fast5 file the issue, tried to convert some more recent fast5 files to pod5 and I was successful

**Comment by HalfPhoton** [comment]
So this problematic fast5 file very old? 

There is potentially a way that we can rescue the signal data from these reads if necessary by using the python API directly and implementing a converter for these old files. 

How many of them do you need to convert?

**Comment by Vsd1106** [comment]
After converting them to multi read fast5 they are 6 files.

**Comment by HalfPhoton** [comment]
Ok, are you able to convert these 6 multi-read fast5s to pod5 now?

Are you going to ignore the single-read fast5s which cannot be converted to multi-read fast5s?

**Comment by Vsd1106** [comment]
I have the same error in regards with those 6 files, even though I removed the single fast5 files that were an issue. 
I assume there might be a conversion issue to multi fast5 but I doesn’t show any errors when converting them

**Comment by HalfPhoton** [comment]
Would you be able to upload one of each of the old single-read fast5s **and** a broken multi-read fast5 files to this link please?

https://nanoporetech.ent.box.com/f/7c4375e2b71b48258ebed29f198b89ab

This will allow me to inspect them and hopefully propose a resolution to this issue.

Kind regards,
Rich

**Comment by Vsd1106** [comment]
Hi Rich, 
Sorry for the late response but I wasn't in the lab until now. I have uploaded a multi-read fast5 broken file(it's called batch_0.fast5) and 2 single read fast5 files that were used to generate one of the 6 multi-read fast5 files.

**Comment by HalfPhoton** [comment]
Thank you very much, we will take a look and get back to you.

**Comment by Vsd1106** [comment]
The files have been uploaded, sorry for the wait but the multi-read fast5 took longer than expected
