### ISSUE TITLE
pod5 convert to_fast5 aborts with Errno 11, flags=13, o_flags=242

### ISSUE THREAD

**Issue by hartnegg** [nanoporetech/pod5-file-format#79]
we get the error
`POD5 has encountered an error: '[Errno 11] Unable to create file (unable to open file: name = '/mnt/host/Sham.fast5/merged.34_0.fast5', errno = 11, error message = 'Resource temporarily unavailable', flags = 13, o_flags = 242)'`

the command was:
`pod5 convert to_fast5 -t 6 -o /mnt/host/Sham.fast5 /mnt/host/xxxx/merged.pod5`

It does create all fast5 files, but some have zero size, and the one mentioned in the error message is the first of those.
When we run it again, some other fast5 files have zero size.

This happened in Ubuntu 22.04, running in a HyperV VM, with data directory on the HyperV-host, mounted to /mnt/host.

I do not know the meaning of those flags, and see no difference after setting the environment variable POD5_DEBUG=1

**Comment by HalfPhoton** [comment]
Hi @hartnegg ,

I've had a look around for what could cause this and it could be due to HDF5 based on [this github thread](https://github.com/h5py/h5py/issues/1220).

The proposed solutions are to;
- Run the command with 'HDF5_USE_FILE_LOCKING=FALSE` 
- Write output in the current working directory `--output .` 

Kind regards, 
Rich
